version: '3'

services:

  rest:
    build:
      context: ./rest
    environment:
      - REST_SERVER=http://64.225.127.211:5000 #if this doesn't work, replace IP with rest
    ports:
      - 6001:6000
    env_file:
      ./credentials.env
    volumes:
      - ./rest/src:/app
    container_name: official_rest_server

  web-server:
    build:
      context: ./web
    ports:
      - 80:6000 # host : container
    env_file:
      ./credentials.env
    volumes:
      - ./web/src:/app
    container_name: agile-web

  db-server:
    image: mysql:latest
    restart: always
    env_file:
      ./credentials.env
    ports:
      - 3306:3306 # host : container
    volumes:
      - ./db:/var/lib/mysql # persistent DB when container is stopped
    container_name: agile-db

volumes:
  database:
